/*
 * This file is generated by jOOQ.
*/
package jp.co.sfk25.annually_report.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.sfk25.annually_report.jooq.Indexes;
import jp.co.sfk25.annually_report.jooq.Keys;
import jp.co.sfk25.annually_report.jooq.Sfk25;
import jp.co.sfk25.annually_report.jooq.tables.records.ArticlesTagsRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticlesTags extends TableImpl<ArticlesTagsRecord> {

    private static final long serialVersionUID = -1014776820;

    /**
     * The reference instance of <code>sfk25.articles_tags</code>
     */
    public static final ArticlesTags ARTICLES_TAGS = new ArticlesTags();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArticlesTagsRecord> getRecordType() {
        return ArticlesTagsRecord.class;
    }

    /**
     * The column <code>sfk25.articles_tags.article_id</code>.
     */
    public final TableField<ArticlesTagsRecord, Integer> ARTICLE_ID = createField("article_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sfk25.articles_tags.tag_id</code>.
     */
    public final TableField<ArticlesTagsRecord, Integer> TAG_ID = createField("tag_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>sfk25.articles_tags</code> table reference
     */
    public ArticlesTags() {
        this(DSL.name("articles_tags"), null);
    }

    /**
     * Create an aliased <code>sfk25.articles_tags</code> table reference
     */
    public ArticlesTags(String alias) {
        this(DSL.name(alias), ARTICLES_TAGS);
    }

    /**
     * Create an aliased <code>sfk25.articles_tags</code> table reference
     */
    public ArticlesTags(Name alias) {
        this(alias, ARTICLES_TAGS);
    }

    private ArticlesTags(Name alias, Table<ArticlesTagsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ArticlesTags(Name alias, Table<ArticlesTagsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sfk25.SFK25;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ARTICLES_TAGS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ArticlesTagsRecord> getPrimaryKey() {
        return Keys.KEY_ARTICLES_TAGS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ArticlesTagsRecord>> getKeys() {
        return Arrays.<UniqueKey<ArticlesTagsRecord>>asList(Keys.KEY_ARTICLES_TAGS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticlesTags as(String alias) {
        return new ArticlesTags(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticlesTags as(Name alias) {
        return new ArticlesTags(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticlesTags rename(String name) {
        return new ArticlesTags(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticlesTags rename(Name name) {
        return new ArticlesTags(name, null);
    }
}
