/*
 * This file is generated by jOOQ.
*/
package jp.co.sfk25.annually_report.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.sfk25.annually_report.jooq.Indexes;
import jp.co.sfk25.annually_report.jooq.Keys;
import jp.co.sfk25.annually_report.jooq.Sfk25;
import jp.co.sfk25.annually_report.jooq.tables.records.LikesRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Likes extends TableImpl<LikesRecord> {

    private static final long serialVersionUID = 97013304;

    /**
     * The reference instance of <code>sfk25.likes</code>
     */
    public static final Likes LIKES = new Likes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LikesRecord> getRecordType() {
        return LikesRecord.class;
    }

    /**
     * The column <code>sfk25.likes.article_id</code>.
     */
    public final TableField<LikesRecord, Integer> ARTICLE_ID = createField("article_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sfk25.likes.user_id</code>.
     */
    public final TableField<LikesRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>sfk25.likes</code> table reference
     */
    public Likes() {
        this(DSL.name("likes"), null);
    }

    /**
     * Create an aliased <code>sfk25.likes</code> table reference
     */
    public Likes(String alias) {
        this(DSL.name(alias), LIKES);
    }

    /**
     * Create an aliased <code>sfk25.likes</code> table reference
     */
    public Likes(Name alias) {
        this(alias, LIKES);
    }

    private Likes(Name alias, Table<LikesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Likes(Name alias, Table<LikesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sfk25.SFK25;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.LIKES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LikesRecord> getPrimaryKey() {
        return Keys.KEY_LIKES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LikesRecord>> getKeys() {
        return Arrays.<UniqueKey<LikesRecord>>asList(Keys.KEY_LIKES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Likes as(String alias) {
        return new Likes(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Likes as(Name alias) {
        return new Likes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Likes rename(String name) {
        return new Likes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Likes rename(Name name) {
        return new Likes(name, null);
    }
}
