/*
 * This file is generated by jOOQ.
*/
package jp.co.sfk25.annually_report.jooq;


import javax.annotation.Generated;

import jp.co.sfk25.annually_report.jooq.tables.Articles;
import jp.co.sfk25.annually_report.jooq.tables.ArticlesTags;
import jp.co.sfk25.annually_report.jooq.tables.Comments;
import jp.co.sfk25.annually_report.jooq.tables.FlywaySchemaHistory;
import jp.co.sfk25.annually_report.jooq.tables.Likes;
import jp.co.sfk25.annually_report.jooq.tables.Tags;
import jp.co.sfk25.annually_report.jooq.tables.Users;


/**
 * Convenience access to all tables in sfk25
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sfk25.articles</code>.
     */
    public static final Articles ARTICLES = jp.co.sfk25.annually_report.jooq.tables.Articles.ARTICLES;

    /**
     * The table <code>sfk25.articles_tags</code>.
     */
    public static final ArticlesTags ARTICLES_TAGS = jp.co.sfk25.annually_report.jooq.tables.ArticlesTags.ARTICLES_TAGS;

    /**
     * The table <code>sfk25.comments</code>.
     */
    public static final Comments COMMENTS = jp.co.sfk25.annually_report.jooq.tables.Comments.COMMENTS;

    /**
     * The table <code>sfk25.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = jp.co.sfk25.annually_report.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>sfk25.likes</code>.
     */
    public static final Likes LIKES = jp.co.sfk25.annually_report.jooq.tables.Likes.LIKES;

    /**
     * The table <code>sfk25.tags</code>.
     */
    public static final Tags TAGS = jp.co.sfk25.annually_report.jooq.tables.Tags.TAGS;

    /**
     * The table <code>sfk25.users</code>.
     */
    public static final Users USERS = jp.co.sfk25.annually_report.jooq.tables.Users.USERS;
}
